name: Release
on:
  push:
    branches:
      - "!**/*"
    tags:
      - "v*.*.*"
      - "v*.*.*-rc*"

permissions:
  pull-requests: write
  packages: write
  contents: write
  actions: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          check-latest: true

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: setup for all services
        run: |
          cp all-services.yaml gen.yaml
          make gen

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v1'
          args: release --clean --skip=validate --timeout=60m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
